<?php /** @var Mage_Page_Block_Html_Pager $this */ ?>
<?php if($this->getShowPerPage()): ?>
<div class="service_content_rowbottom_left">
    <label class="service_content_group_title">SHOW</label>
    <select class="custom_select" onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableLimit() as $key => $limit): ?>
        <option value="<?php echo $this->getLimitUrl($key) ?>"<?=$this->isLimitCurrent($key) ? ' selected' : ''?>><?=$limit?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
<div class="service_content_rowbottom_right">
    <?php if($this->getLastPageNum()>0): ?>
    <ul class="paginator">
        <?php if ($this->canShowFirst()): ?>
            <li><a href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
        <?php endif;?>

        <?php if ($this->canShowPreviousJump()): ?>
            <li><a href="<?php echo $this->getPreviousJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php foreach ($this->getFramePages() as $_page): ?>
            <?php if ($this->isPageCurrent($_page)): ?>
                <li class="active"><a href="#"><?php echo $_page ?></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
            <?php endif;?>
        <?php endforeach;?>

        <?php if ($this->canShowNextJump()): ?>
            <li><a href="<?php echo $this->getNextJumpUrl() ?>">...</a></li>
        <?php endif;?>

        <?php if ($this->canShowLast()): ?>
            <li><a href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
        <?php endif;?>
    </ul>
    <?php endif; ?>
</div>