<div class="modal fade" id="popup-confirm-modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="popup-confirm-modal">
                <div class="page-title">
                    <p class="confirm-message"></p>
                </div>
                <button type="button" class="confirm button" ><?php echo $this->__('Yes') ?></button>
                <button type="button" class="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></button>
            </div>
        </div>
    </div>
</div>
