<div class="modal fade" id="addressbook-address-select-modal" role="dialog">
    <div class="modal-dialog ad">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Address Book</h4>
            </div>
            <div class="modal-body">
                <?php echo $this->getChildHtml('grid') ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="button btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="button btn btn-default" onclick="addressbook.submit(this)">OK</button>
            </div>
        </div>
    </div>
</div>
<script>
    var addressbook = new AddressBook('addressbook-address-select-modal', <?php echo $this->getMultiple() ? 'true' : 'false' ?>);
</script>