<section class="track_order">
    <div class="track_order_container">
        <h6>SHIPPING</h6>
        <h2>TRACK MY ORDER</h2>
        <p>Find My Order</p>
        <form class="order_number" name="order_number">
            <input type="" placeholder="Order #" name="order" autocomplete="off">
            <button id="find-order" type="button"><span>FIND</span></button>
        </form>
    </div>
    <div class="triangle">
        <i class="fas fa-chevron-down"></i>
    </div>
</section>
<section class="shipping-status" style="display: none;">
    <div class="shipping-status-container"></div>
</section>