<?php
/**
 * @var Sellry_OrderSync_Block_Adminhtml_Ordersync_View $this
 */
?>

<?php $event = $this->getEvent() ?>

<div class="content-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-9">
                <?php echo $this->getHeaderHtml() ?>
                <ul class="breadcrumb">
                    <li>
                        <a href="<?php echo $this->getBaseUrl().'admin'; ?>">Dashboard</a>
                    </li>
                    <li>
                        <span><?php echo $this->getHeaderHtml() ?></span>
                    </li>
                </ul>
            </div>
            <div class="col-sm-6 col-xs-3 form-buttons">
                <?php echo $this->getBackButtonHtml() ?>
                <?php if($this->getEventId()): ?>
                    <?php echo $this->getDeleteButtonHtml() ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <!--Order Information-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account">Event Information</h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody><tr>
                        <td class="label"><label>Event Date</label></td>
                        <td class="value"><strong><?=$event->getProcessedTime()?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label>Event Status</label></td>
                        <td class="value"><strong><?=$event->getStatus()?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label>Username</label></td>
                        <td class="value"><strong><?=$event->getUsername()?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label>Password</label></td>
                        <td class="value"><strong><?=$event->getPassord()?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label>Host</label></td>
                        <td class="value"><strong><?=$event->getHost()?></strong></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <?php echo $this->getStatisticBlockHtml() ?>
</div>
<div class="row">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account">Files</h4>
            <div class="tools"></div>
        </div>
        <div class="grid np">
            <div class="hor-scroll">
                <table cellspacing="0" class="data order-tables">
                    <colgroup><col width="1">
                        <col>
                        <col>
                        <col>
                        <col width="1">
                    </colgroup><thead>
                    <tr class="headings">
                        <th>Id</th>
                        <th><span class="nobr">Name</span></th>
                        <th><span class="nobr">Type</span></th>
                        <th>Date</th>
                        <th class="a-center">Action</th>
                    </tr>
                    </thead>
                    <tbody class="">
                    <?php $even = false; $i = 0; foreach($this->getFilesCollection() as $file): ?>
                    <?php if (!$file->exists()) continue; ?>
                    <tr class="border<?=$i % 2 == 0 ? ' even' : '' ?>">
                        <td class="a-left"><?=$file->getId()?></td>
                        <td>
                            <div id="event_item_<?=$i?>" class="item-container">
                                <div class="item-text">
                                    <h5 class="title"><span id="order_item_<?=$i?>_title"><?=$file->getDownloadName()?></span></h5>
                                </div>
                            </div>
                        </td>
                        <td class="a-right"><?=$file->getType()?></td>
                        <td class="a-right"><?=$file->getDate()?></td>
                        <td><a href="<?=$this->getDownloadAction($file->getPath())?>">Download</a></td>
                    </tr>
                    </tbody>
                    <?php $i++; endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
