<?php

class Blackbox_Epace_Model_Epace_Job_Part_PressForm extends Blackbox_Epace_Model_Epace_Job_Part_AbstractChild
{
    protected function _construct()
    {
        $this->_init('JobPartPressForm', 'id');
    }

    public function getDefinition()
    {
        return [
            'id' => 'int',
            'orientation' => '',
            'metrixID' => '',
            'metrixComponentID' => '',
            'job' => '',
            'jobPart' => '',
            'formNum' => '',
            'numPasses' => '',
            'coating' => 'bool',
            'varnish' => 'bool',
            'qtyToMfg' => '',
            'description' => '',
            'runSizeHeight' => '',
            'runSizeWidth' => '',
            'numUp' => '',
            'materialUp' => '',
            'press' => '',
            'runMethod' => '',
            'pressSheets' => '',
            'makeReadySheets' => '',
            'offPressQty' => '',
            'runImpressions' => '',
            'impressionsPerHour' => '',
            'runSpoilageSheets' => '',
            'numSigs' => '',
            'time' => 'float',
            'plate' => '',
            'registration' => '',
            'numAcross' => '',
            'numAlong' => '',
            'liftChange' => '',
            'runHours' => '',
            'finishingMakeReadySheets' => '',
            'finishingRunSpoilageSheets' => '',
            'makeReadyHours' => '',
            'washupHours' => '',
            'otherHours' => '',
            'colorsSide1' => '',
            'colorsSide2' => '',
            'colorsTotal' => '',
            'numPlates' => '',
            'jobMaterial' => '',
            'jdfSubmitted' => 'bool',
            'numBlanks' => '',
            'pageCount' => '',
            'sheetCount' => '',
            'run' => '',
            'useLegacyPrintFlowFormat' => 'bool',
            'body' => 'bool',
            'pages' => '',
            'foldPattern' => '',
            'secondWeb' => 'bool',
            'displaySortOrder' => '',
            'layoutSide1' => '',
            'paceConnectFileType' => '',
            'estimateSource' => '',
            'nonPrinted' => 'bool',
            'colorSplit' => 'bool',
            'twoUpSplit' => 'bool',
            'attributeSplit' => 'bool',
            'pressIndicator' => '',
            'printRunMethod' => '',
            'grainDirection' => '',
            'filterPressEventsByPress' => 'bool',
            'inkCoatingDry' => 'bool',
            'inkVarnishDry' => 'bool',
            'beg' => '',
            'end' => '',
            'runs' => '',
            'colors' => '',
            'gangedRun' => 'bool',
            'runSize' => '',
            'splitDescription' => '',
            'quantityRemaining' => '',
            'scheduled' => 'bool',
            'JobPartKey' => '',
            'foldPatternKey' => '',
        ];
    }
}