<?php

class Blackbox_CinemaCloud_Model_Core_Layout extends Mage_Core_Model_Layout
{
    protected function _generateAction($node, $parent)
    {
        $attributes = $node->attributes();
        if (isset($attributes['ifhelper']) && ($helperAction = (string)$attributes['ifhelper'])) {
            $exploded = explode('::', $helperAction);
            if (count($exploded) != 2) {
                Mage::throwException('Invalid ifhelper layout attribute: ' . $helperAction);
            }

            if (!Mage::helper($exploded[0])->{$exploded[1]}()) {
                return $this;
            }
        }
        return parent::_generateAction($node, $parent); // TODO: Change the autogenerated stub
    }
}