<?php
/** @var Mage_Checkout_Block_Onepage_Billing $this */
$address = $this->getAddress();
?>
<form id="checkout_billing_form">
    <div class="payment_title">Billing address</div>
    <?php if ($this->customerHasAddresses()): ?>
        <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
        <div class="input-box">
            <?php echo $this->getAddressesHtmlSelect('billing') ?>
        </div>
    <?php endif; ?>
    <div>
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
        <div class="paymentinformation_group">
            <div class="title13">First Name</div><input class="input_border <?php echo $this->helper('customer/address')->getAttributeValidationClass('firstname') ?>" type="text" name="billing[firstname]" value="<?=$this->escapeHtml($address->getFirstname())?>">
        </div>
        <div class="paymentinformation_group">
            <div class="title13">Last Name</div><input class="input_border <?php echo $this->helper('customer/address')->getAttributeValidationClass('lastname') ?>" type="text" name="billing[lastname]" value="<?=$this->escapeHtml($address->getLastname())?>">
        </div>
        <div class="paymentinformation_group">
            <div class="title13">Email</div><input class="input_border required-entry validate-email" name="billing[email]" type="text" value="<?=$this->escapeHtml($address->getEmail())?>">
        </div>
        <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
        <div class="paymentinformation_group">
            <div class="title13">Address line 1</div><input class="input_border <?php echo $_streetValidationClass ?>" type="text" name="billing[street][]" value="<?=$this->escapeHtml($address->getStreet1())?>">
        </div>
        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
        <div class="paymentinformation_group">
            <div class="title13">address line <?=$_i?> (optional)</div><input class="input_border <?php echo $_streetValidationClass ?>" type="text" name="billing[street][]" value="<?=$this->escapeHtml($address->getStreet($_i))?>">
        </div>
        <?php endfor; ?>
        <div class="paymentinformation_group">
            <div class="title13">City / town</div><input class="input_border <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" type="text" name="billing[city]" value="<?=$this->escapeHtml($address->getCity())?>">
        </div>
        <div class="paymentinformation_group">
            <div class="title13">Country</div><?php echo $this->getCountryHtmlSelect('billing') ?>
        </div>
        <div class="paymentinformation_group">
            <div class="title13">state</div>
            <select id="billing:region_id" name="billing[region_id]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script type="text/javascript">
                //<![CDATA[
                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
            </script>
            <input id="billing:region" name="billing[region]" class="input_border <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" type="text" value="<?=$this->escapeHtml($address->getRegion())?>" style="display:none;">
        </div>
        <div class="paymentinformation_group required-entry">
            <div class="title13">postal / zip code</div><input class="input_border validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" name="billing[postcode]" id="billing:postcode"  type="text" value="<?=$this->escapeHtml($address->getPostcode())?>">
        </div>
        <div class="paymentinformation_group required-entry">
            <div class="title13">telephone</div><input class="input_border <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" name="billing[telephone]" id="billing:telephone"  type="text" value="<?=$this->escapeHtml($address->getTelephone())?>">
        </div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var billing = new function () {
        this.newAddress = function(i) {

        }
    };
    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    //]]>
</script>