<?php /** @var Mage_Adminhtml_Block_Template $this */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
    <title>Cinema Works Login Page</title>
    <link href="<?php echo $this->getSkinUrl('css/bootstrap-grid.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->getSkinUrl('css/main.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->getSkinUrl('css/great_profile.css') ?>" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="<?php echo $this->getSkinUrl('js/html5shiv.min.js') ?>" type="text/javascript"></script>
    <script src="<?php echo $this->getSkinUrl('js/respond.min.js') ?>" type="text/javascript"></script>
    <![endif]-->
</head>
<body>
<section class="great_profile">
    <div class="great_profile_img">
        <div class="great_profile_image great_profile_img_big" style="background-image: url(<?php echo $this->getSkinUrl('images/CinemaWorks1_1.png') ?>)"></div>
        <div class="great_profile_image great_profile_img_small" style="background-image: url(<?php echo $this->getSkinUrl('images/CinemaWorks1_2.png') ?>)"></div>
    </div>
    <div class="great_profile_login">
        <div class="great_profile_login_img" style="background-image: url(<?php echo $this->getSkinUrl('images/CinemaWorks2_1.png')?>)"></div>
        <div class="great_profile__login"><a class="great_profile_logo" href="/"></a>
            <?php echo $this->getMessagesBlock()->toHtml() ?>
            <form action="/customer/account/loginPost" method="post">
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                <input type="text" name="login[username]" placeholder="Name">
                <input type="password" name="login[password]" placeholder="Password">
                <div class="tac great_profile_button">
                    <button class="button button_grey">Login</button>
                </div>
            </form>
            <div class="great_profile_login_text_login tac"><a href="/customer/account/forgotPassword">Forgot a password?</a></div>
        </div>
        <div class="great_profile_login_img" style="background-image: url(<?php echo $this->getSkinUrl('images/CinemaWorks2_3.png') ?>)"></div>
    </div>
    <div class="great_profile_img">
        <div class="great_profile_image great_profile_img_small" style="background-image: url(<?php echo $this->getSkinUrl('images/CinemaWorks3_1.png') ?>)"></div>
        <div class="great_profile_image great_profile_img_big" style="background-image: url(<?php echo $this->getSkinUrl('images/CinemaWorks3_2.png') ?>)"></div>
    </div>
</section>
<script src="<?php echo $this->getSkinUrl('js/jquery.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/bootstrap.min.js' )?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/masonry.js' )?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/circle-progress.min.js' )?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl('js/scripts.js' )?>" type="text/javascript"></script>
</body>
</html>
