<?php
/* @var Blackbox_OrderApproval_Block_Adminhtml_Order_Approval_Create_Items $this */
?>
<?php $_canViewPrices = !Mage::helper('core')->isModuleEnabled('Blackbox_RolesPermissions') || Mage::helper('rolespermissions')->canViewPrices(); ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <?php if ($_canViewPrices): ?>
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo Mage::helper('sales')->__('Product') ?></th>
                <?php if ($_canViewPrices): ?>
                <th><?php echo Mage::helper('sales')->__('Price') ?></th>
                <th class="a-center"><?php echo Mage::helper('sales')->__('Qty') ?></th>
                <th><span class="nobr"><?php echo Mage::helper('sales')->__('Qty to Approve') ?></span></th>
                <th><?php echo Mage::helper('sales')->__('Subtotal') ?></th>
                <th><span class="nobr"><?php echo Mage::helper('sales')->__('Tax Amount') ?></span></th>
                <th><span class="nobr"><?php echo Mage::helper('sales')->__('Discount Amount') ?></span></th>
                <th class="last"><span class="nobr"><?php echo Mage::helper('sales')->__('Row Total') ?></span></th>
                <?php else: ?>
                    <th class="a-center"><?php echo Mage::helper('sales')->__('Qty') ?></th>
                    <th class="last"><span class="nobr"><?php echo Mage::helper('sales')->__('Qty to Approve') ?></span></th>
                <?php endif; ?>
            </tr>
        </thead>
        <?php if ($this->canEditQty()): ?>
        <tfoot>
            <tr>
                <td colspan="2">&nbsp;</td>
            <?php if ($_canViewPrices): ?>
                <td colspan="3" class="a-center"><?php echo $this->getUpdateButtonHtml() ?></td>
                <td colspan="3">&nbsp;</td>
            <?php else: ?>
                <td colspan="1"><?php echo $this->getUpdateButtonHtml() ?></td>
            <?php endif; ?>
            </tr>
        </tfoot>
        <?php endif; ?>
        <?php $_items = $this->getApproval()->getAllItems() ?>
        <?php $_i=0;foreach ($_items as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) continue; else $_i++; ?>
        <tbody class="<?php echo $_i%2?'even':'odd' ?>">
            <?php echo $this->getItemHtml($_item) ?>
            <?php echo $this->getItemExtraInfoHtml($_item->getOrderItem()) ?>
        </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
<br />
<?php if ($_canViewPrices): ?>
<div class="clear"></div>
<?php echo $this->getChildHtml('order_totalbar') ?>
<div class="clear"></div>
<?php endif; ?>

<div class="box-left entry-edit">
    <div class="entry-edit-head"><h4><?php echo $this->__('Approval History') ?></h4></div>
    <fieldset>
        <div id="history_form" class="order-history-form">
            <span class="field-row">
                <label class="normal" for="approval_comment_text"><?php echo Mage::helper('sales')->__('Approval Comments') ?></label>
                <textarea id="approval_comment_text" name="approval[comment_text]" rows="3" cols="5" style="height:10em; width:98%;"><?php echo $this->getApproval()->getCommentText(); ?></textarea>
            </span>
            <div class="clear"></div>
        </div>
    </fieldset>
</div>

<div class="box-right entry-edit" id="approval_totals">
    <div class="entry-edit-head"><h4><?php echo $this->__('Approval Totals') ?></h4></div>
    <div class="order-totals">
        <div class="order-totals-bottom">
          <div class="divider"></div>
          <?php if ($this->canSendApprovalEmail()): ?>
          <p>
              <label class="normal" for="send_email"><?php echo Mage::helper('sales')->__('Email Copy of Approval') ?></label>
              <input id="send_email" name="approval[send_email]" value="1" type="checkbox" />
          </p>
          <?php endif; ?>
          <div class="a-right">
          <?php echo $this->getChildHtml('submit_button') ?>
          </div>
        </div>
    </div>
</div>
<div class="clear"></div>

<table class="order-info-foot" cellpadding="10" cellspacing="0" width="100%">
    <tbody>
        <tr>
            <td class="section">
                <table id="comments_block" cellpadding="0" width="100%">
                    <tbody>
                        <tr>
                            <td style="padding-right:30px; width:50%;">&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </td>
            <td class="document-totals section">&nbsp;</td>
        </tr>
    </tbody>
</table>

<script type="text/javascript">
//<![CDATA[
var submitButtons = $$('.submit-button');
var updateButtons = $$('.update-button');
var enableSubmitButtons = <?php echo (int) !$this->getDisableSubmitButton() ?>;
var fields = $$('.qty-input');

updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});

for(var i=0;i<fields.length;i++){
    fields[i].observe('change', checkButtonsRelation)
    fields[i].baseValue = fields[i].value;
}

function checkButtonsRelation() {
    var hasChanges = false;
    fields.each(function (elem) {
        if (elem.baseValue != elem.value) {
            hasChanges = true;
        }
    }.bind(this));
    if (hasChanges) {
        submitButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
    }
    else {
        if (enableSubmitButtons) {
            submitButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
        }
        updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
    }
}

var sendEmailCheckbox = $('send_email');
if (sendEmailCheckbox) {
    var notifyCustomerCheckbox = $('notify_customer');
    var approvalCommentText = $('approval_comment_text');
    Event.observe(sendEmailCheckbox, 'change', bindSendEmail);
    bindSendEmail();
}
function bindSendEmail()
{
    if (sendEmailCheckbox.checked == true) {
        notifyCustomerCheckbox.disabled = false;
        //approvalCommentText.disabled = false;
    }
    else {
        notifyCustomerCheckbox.disabled = true;
        //approvalCommentText.disabled = true;
    }
}
//]]>
</script>
