<?php  $_order = $this->getOrder() ?>
<?php $disapproval = $this->getParentBlock()->getDisapproval() ?>
<a href="<?php echo $this->getUrl('*/*/cancel', array('disapproval_id' => $disapproval->getId())) ?>" class="link-rss f-none" onclick="if (!confirm('<?php echo $this->__('Are you sure?') ?>')) event.preventDefault()"><?php echo $this->__('Cancel Order') ?></a>
<span class="separator">|</span>
<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
    <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss f-none"><?php echo $this->__('Subscribe to Order Status') ?></a>
    <span class="separator">|</span>
<?php endif; ?>
<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
    <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
    <span class="separator">|</span>
<?php endif ?>
<a href="<?php echo $this->getPrintUrl($_order) ?>" class="link-print" onclick="this.target='_blank';"><?php echo $this->__('Print Order') ?></a>
<?php echo $this->getChildHtml(); ?>
