<section class="support-ticket">
    <div class="support-ticket-inner main-container">
        <div class="breadcrumbs top-text">
            <ul>
                <li class="home">
                    <a href="<?php echo $this->getBaseUrl(); ?>" title="Go to Home Page"><p>Home</p></a>
                    <div class="red_dot"></div>
                </li>
                <li class="contacts">
                    <p>Support</p>
                </li>
            </ul>
        </div>
        <div class="page-title">
            <h2>Support Ticket</h2>
        </div>
        <form action="<?php echo $this->getFormAction(); ?>" id="supportForm" method="post" class="scaffold-form">
            <div class="fieldset">
                <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required">Please Select Request Type</label>
                            <div class="input-box select-box">
                                <select name="request-type" id="request-type" title="request type" class="input-text required-entry">
                                    <option value="" disabled selected hidden>Please Select Request Type</option>
                                    <option value="">1</option>
                                    <option value="">2</option>
                                    <option value="">3</option>
                                    <option value="">4</option>
                                </select>
                                <i class="fas fa-chevron-down "></i>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required"><?php echo Mage::helper('contacts')->__('Name') ?></label>
                            <div class="input-box">
                                <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                            </div>
                        </div>
                    </li>
                    <li class="phone-number">
                        <label for="telephone"><?php echo Mage::helper('contacts')->__('Phone Number') ?></label>
                        <div class="input-box">
                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Phone Number')) ?>" value="" class="input-text" type="tel" />
                        </div>
                    </li>
                    <li class="email">
                        <div class="field">
                            <label for="email" class="required"><?php echo Mage::helper('contacts')->__('Email') ?></label>
                            <div class="input-box">
                                <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                            </div>
                        </div>
                    </li>
                    <li class="wide comment-text">
                        <label for="comment" class="required"><?php echo Mage::helper('contacts')->__('Brief Decsription') ?></label>
                        <div class="input-box">
                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Brief Decsription')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Send')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Send') ?></span></span></button>
            </div>
        </form>
    </div>
</section>