<section class="printing-category">
    <div class="printing-category-top">
        <h2>PRINTING CATEGORY</h2>
        <p class="printing-category-top-desc">Order your print needs on the go. Most orders have 5 day turnaround<br>
            with standard shipping. Plan accordingly and make sure you don’t run out!</p>
        <div class="printing-category-top-circles mobile-hide">
            <div class="MENU">
                <a href="<?php echo Mage::getModel("catalog/category")->load(8)->getUrl();?>">
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                <p>MENU</p>
                </a>
            </div>
            <div class="SIGNAGE">
                <a href="<?php echo Mage::getModel("catalog/category")->load(3)->getUrl();?>">
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                <p>SIGNAGE</p>
                </a>
            </div>
            <div class="MARKETING">
                <a href="<?php echo Mage::getModel("catalog/category")->load(9)->getUrl();?>">
                    <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                <p>MARKETING &<br>
                    PROMOTION</p>
                </a>
            </div>
            <div class="CATERING">
                <a href="<?php echo Mage::getModel("catalog/category")->load(10)->getUrl();?>">
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                <p>CATERING</p>
                </a>
            </div>
            <div class="STATIONARY">
                <a href="<?php echo Mage::getModel("catalog/category")->load(11)->getUrl();?>">
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                <p>STATIONARY</p>
                </a>
            </div>
            <div class="KIT">
                <a href="<?php echo Mage::getModel("catalog/category")->load(12)->getUrl();?>">
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                <p>KITS</p>
                </a>
            </div>
        </div>
        <div class="printing-category-top-circles-mob mobile-show">
            <div class="owl-carousel owl-theme">
                <div class="item MENU">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(8)->getUrl();?>">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                    <p>MENU</p>
                    </a>
                </div>
                <div class="item SIGNAGE">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(3)->getUrl();?>">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                    <p>SIGNAGE</p>
                    </a>
                </div>
                <div class="item MARKETING">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(9)->getUrl();?>">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                        <p>MARKETING &<br>
                            PROMOTION</p>
                    </a>
                </div>
                <div class="item CATERING">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(10)->getUrl();?>">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                    <p>CATERING</p>
                    </a>
                </div>
                <div class="item STATIONARY">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(11)->getUrl();?>">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                    <p>STATIONARY</p>
                    </a>
                </div>
                <div class="item KIT">
                    <a href="<?php echo Mage::getModel("catalog/category")->load(12)->getUrl();?>">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                    <p>KITS</p>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="printing-category-grid">
        <div class="printing-category-grid-container">
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid1.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-menu.png'); ?>"
                             alt="">
                        <p class="red">MENU</p>
                        <p class="descr">paper to-go menus &<br>
                            nutritional and allergen<br>
                            information cards</p>
                        <a href="<?php echo Mage::getModel("catalog/category")->load(8)->getUrl();?>">
                            <button class="tg-more">more</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-signage.png'); ?>"
                             alt="">
                        <p class="red">SIGNAGE</p>
                        <p class="descr">in store, food, drink signs, sign<br>
                            holders & wall menu boards</p>
                        <a href="<?php echo Mage::getModel("catalog/category")->load(3)->getUrl();?>">
                            <button class="tg-more">more</button>
                        </a>
                    </div>
                </div>
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid2.png'); ?>" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid3.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 bg-aqua">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-marketing.png'); ?>"
                             alt="">
                        <p class="white">MARKETING &<br>
                            PROMOTION</p>
                        <p class="descr">coupons, kindness cards &<br>
                            event promotion collateral</p>
                        <a href="<?php echo Mage::getModel("catalog/category")->load(9)->getUrl();?>">
                            <button class="tg-more">more</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 bg-yellow">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-catering.png'); ?>"
                             alt="">
                        <p class="cat"></p>
                        <p class="white">CATERING</p>
                        <p class="descr">catering sticker labels, tent cards,<br>
                            tape & additional print items</p>
                        <a href="<?php echo Mage::getModel("catalog/category")->load(10)->getUrl();?>">
                            <button class="tg-more">more</button>
                        </a>
                    </div>
                </div>
                <div class="col-6 col-small-12 right">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid4.png'); ?>" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid5.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-stationary.png'); ?>"
                             alt="">
                        <p class="cat"></p>
                        <p class="red">STATIONARY</p>
                        <p class="descr">business cards, buckslips &<br>
                            additional writing items</p>
                        <a href="<?php echo Mage::getModel("catalog/category")->load(11)->getUrl();?>">
                            <button class="tg-more">more</button>
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 bg-grey">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-kit.png'); ?>" alt="">
                        <p class="cat"></p>
                        <p class="red">KITS</p>
                        <p class="descr">catering stickers, catering<br>
                            tent cards, tapes & new<br>
                            store opening kits</p>
                        <a href="<?php echo Mage::getModel("catalog/category")->load(12)->getUrl();?>">
                            <button class="tg-more">more</button>
                        </a>
                    </div>
                </div>
                <div class="col-6 col-small-12 right">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid6.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<?php echo $this->getLayout()->createBlock('tendergreens/tracking')->toHtml() ?>

<section class="printing-demand">
    <div class="printing-demand-container">
        <h6>your design</h6>
        <h2>template<br>
            generation</h2>
        <button class="tg-button" type="button">Create</button>

    </div>
</section>

<section class="order-request">
    <div class="order-request-container">
        <h6>order</h6>
        <h2>CUSTOM ORDER <br>
            REQUEST</h2>
        <button class="tg-button" type="button">Order</button>

    </div>
</section>
<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
<section class="help-poc">
    <div class="help-poc-container">
        <h6>for client</h6>
        <h2>help-poc</h2>
        <p>Sign In</p>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <form  action="<?php echo $this->getUrl('customer/account/loginPost/') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey'); ?>
            <input type="email" autocomplete="off" placeholder="E-mail"  name="login[username]" id="email" class="help-poc-input required-entry validate-email" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" />
            <input type="password" autocomplete="off" placeholder="Password" name="login[password]" class="help-poc-input required-entry validate-password" id="pass" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" />
            <?php echo $this->getChildHtml('form.additional.info'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

            <button type="submit" class="tg-button button" title="<?php echo $this->quoteEscape($this->__('Login')) ?>" name="send" id="send2"><?php echo $this->__('Login') ?></button>
        </form>
    </div>
</section>
<?php endif;?>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('login-form', true);
    //]]>
</script>
<script>
    jQuery(document).ready(function () {
        jQuery('.owl-carousel').owlCarousel({
            items: 1,
            margin: 10,
            autoHeight: true
        });
    })
</script>