<div class="footer">
    <div class="tg-footer-container">
        <img class="footer-logo" src="<?php echo $this->getSkinUrl('images/tg-footer.png'); ?>" alt="">
        <h6>community</h6>
        <div class="social-links">
            <a href="https://www.instagram.com/tendergreens/">
                <div class="soc-circ">
                    <i class="fab fa-instagram"></i>
                </div>
            </a>
            <a href="https://www.facebook.com/tendergreensfood">
                <div class="soc-circ">
                    <i class="fab fa-facebook-f"></i>
                </div>
            </a>
            <a href="https://twitter.com/tendergreens">
                <div class="soc-circ">
                    <i class="fab fa-twitter"></i>
                </div>
            </a>
            <a href="https://www.youtube.com/user/tendergreensfood">
                <div class="soc-circ">
                    <i class="fab fa-youtube"></i>
                </div>
            </a>
        </div>
        <address class="copyright"><?php echo $this->getCopyright() ?></address>
    </div>
</div>