
<div class="headship">
    <div class="trackheader">
        <h1> TRACK PROGRESS</h1>
    </div>

    <div class="shipping-status-track" >
        <div class = "ordernum">
            <h4>ORDER # 300010</h4>
        </div>


        <div class="progress-bar-order progress-first-step-track ">

            <div class="points-progress">
                <div class="progress-point ">

                    <div class="progress-point-circle-track">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <div class="buttracktext1">
                        <p class="current-step-track">SHIPPING<br> 08 May,2018</p></div>
                </div>
                <div class="progress-point">

                    <div class="progress-point-circle-track">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <div class="buttracktext2">
                        <p>ORDER<br>INFORMATION</p></div>
                </div>
                <div class="progress-point">

                    <div class="progress-point-circle-track">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <div class="buttracktext3">
                        <p>ORDER<br>DELIVERY</p></div>
                </div>
                <div class="progress-point">

                    <div class="progress-point-circle-track">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <div class="buttracktext4">
                        <p>COURIER<br> DELIVERY </p></div>
                </div>
                <div class="progress-point">

                    <div class="progress-point-circle-track">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <div class="buttracktext5">
                        <p>ORDER<br> ISSUED</p></div>
                </div>
            </div>
        </div>
    </div>




    <div class= "track-table">
        <div class = "track-table-row">
            <div class = "track-column1">
                <h5>PRODUCT NAME</h5>
            </div>
            <div class = "track-column2">
                <h5>LINK</h5>
            </div>
            <div class = "track-column3">
                <h5>PRODUCT SKU</h5>
            </div>
            <div class = "track-column4">
                <h5>PURCHASES</h5>
            </div>
            <div class = "track-column5">
                <h5>DOWNLOADS</h5>
            </div>
        </div>

        <div class="track-table-row2">
            <div class = "track-column1">
                <p>OTR Industrial Tires Brochure</p>
            </div>
            <div class = "track-column2">
                <p><a href="download.html">Download</span></a></p>
            </div>
            <div class = "track-column3">
                <p>OTS-0369</p>
            </div>
            <div class = "track-column4">
                <p>Unlimited</p>
            </div>
            <div class = "track-column5">
                <p>1</p>
            </div>
        </div>
        <div class="track-table-row3">
            <div class = "track-column1">
                <p>OTR Industrial Tires Brochure</p>
            </div>
            <div class = "track-column2">
                <p><a href="download.html">Download</span></a></p>
            </div>
            <div class = "track-column3">
                <p>OTS-0369</p>
            </div>
            <div class = "track-column4">
                <p>Unlimited</p>
            </div>
            <div class = "track-column5">
                <p>1</p>
            </div>
        </div>
    </div>


    <div class= "track-mobile">
        <div class="mobileheader">
            <h4>YOUR SHIPPING STATUS</h4></div>
        <div class = "mobile-ordernum">
            <h5>ORDER # 300010</h5>
        </div>
        <div class="progress-bar-order progress-first-step-track">
            <div class="points-progress">
                <div class="progress-point ">

                    <div class="progress-point-circle-track">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <div class="buttracktext1 step1">
                        <p class="current-step-track">SHIPPING 08 May,2018</p>
                    </div>
                    <div class="buttracktext1 step2">
                        <p class="current-step-track">ORDER INFORMATION</p>
                    </div>
                    <div class="buttracktext1 step3">
                        <p class="current-step-track">ORDER DELIVERY</p>
                    </div>
                    <div class="buttracktext1 step4">
                        <p class="current-step-track">COURIER DELIVERY</p>
                    </div>
                    <div class="buttracktext1 step5">
                        <p class="current-step-track">ORDER ISSUED</p>
                    </div>
                </div>
            </div>
        </div>


        <div class="track-mobile-table1">
            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Product Name:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>OTR Industrial Tires Brochure</p>
                </div>
            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Link:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p> <p><a href="download.html">Download</a></p></p>
                </div>

            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Product SKU:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>OTS-0369</p>
                </div>

            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Purchases:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>Unlimited</p>
                </div>

            </div>

            <div class = "track-mobile-table-row-last">
                <div class = "track-mobile-column1">
                    <h5>DWN:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>1</p>
                </div>
            </div>
        </div>

        <div class="track-mobile-table2">
            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Product Name:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>OTR Industrial Tires Brochure</p>
                </div>
            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Link:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p> <p><a href="download.html">Download</a></p></p>
                </div>

            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Product SKU:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>OTS-0369</p>
                </div>

            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Purchases:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>Unlimited</p>
                </div>

            </div>


            <div class = "track-mobile-table-row-last">
                <div class = "track-mobile-column1">
                    <h5>DWN:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>1</p>
                </div>
            </div>
        </div>

        <div class="track-mobile-table3">
            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Product Name:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>OTR Industrial Tires Brochure</p>
                </div>
            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Link:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p> <p><a href="download.html">Download</a></p></p>
                </div>

            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Product SKU:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>OTS-0369</p>
                </div>

            </div>

            <div class = "track-mobile-table-row">
                <div class = "track-mobile-column1">
                    <h5>Purchases:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>Unlimited</p>
                </div>

            </div>


            <div class = "track-mobile-table-row-last">
                <div class = "track-mobile-column1">
                    <h5>DWN:</h5>
                </div>
                <div class = "track-mobile-column2">
                    <p>1</p>
                </div>
            </div>

        </div>


    </div>



    <div class="but">
        <div class="buttonnum1">
            <button class="buttonde" ><span>Feedback</span></button>
        </div>
        <div class="buttonnum2">
            <button class="buttond" ><span>Accept</span></button>
        </div>

    </div>
</div>
