<?php

class Blackbox_CinemaCloud_Controller_Router_Cinemacloud extends Mage_Core_Controller_Varien_Router_Standard
{
    public function collectRoutes($configArea, $useRouterName)
    {
        parent::collectRoutes($configArea, $useRouterName); // TODO: Change the autogenerated stub
    }

    public function match(Zend_Controller_Request_Http $request)
    {
        if (!parent::match($request)) {
            return false;
        }
        return true;
    }

    public function fetchDefault()
    {
        $this->getFront()->setDefault(array(
            'module' => 'cms',
            'controller' => 'index',
            'action' => 'index'
        ));
    }

    public function _getDefaultPath()
    {
        return 'customer/account/login';
    }
}