<?php $_item = $this->getItem() ?>
<?php $this->setPriceDataObject($_item) ?>
<tr>
    <td>
        <?php if ($this->canDisplayContainer()): ?>
        <div id="<?php echo $this->getHtmlId() ?>" class="item-container">
        <?php endif; ?>
        <div class="item-text">
            <?php echo $this->getColumnHtml($_item, 'name') ?>
        </div>
        <?php if ($this->canDisplayContainer()): ?>
        </div>
        <?php endif ?>
    </td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('price') ?> <?=$this->escapeHtml($_item->getUom())?></td>
    <td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="a-right"><?php echo $this->displayTaxPercent($_item) ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('extended_price') ?></td>
</tr>
