<script>
    //<![CDATA[
    $('<?=$this->getScope()?>').addEventListener("change", function() {
        rule_actions_fieldset.changeScope(this.value, $("<?=$this->getFieldset()?>"));
    });
    rule_actions_fieldset.changeScope = function(scope, fieldset) {
        new Ajax.Request("<?=$this->getAjaxUrl()?>", {
            evalScripts: true,
            parameters: {form_key: FORM_KEY, scope: scope },
            onComplete: this.onAddNewChildComplete.bind(this, fieldset),
            onSuccess: function(transport) {
                if(this._processSuccess(transport)) {
                    fieldset.update(transport.responseText);
                }
            }.bind(this),
            onFailure: this._processFailure.bind(this)
        });
    };
    //]]>
</script>