<?php /** @var Blackbox_TenderGreens_Block_Tracking_Progress $this */ ?>
<h3>Your shipping status</h3>
<div class="progress-bar-order progress-<?php echo $this->getProgressBarStep()?>-step mobile-hide">
    <div class="progress progress-striped">
        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="100" aria-valuemin="0"
             aria-valuemax="100">
        </div>
    </div>
    <div class="points-progress">
    <?php $i = 0; foreach($this->getProgressPoints() as $point): $i++; ?>
        <div class="progress-point">
            <h6><?php echo str_pad($i, 2, '0', STR_PAD_LEFT) ?></h6>
            <div class="progress-point-circle">
                <i class="fas fa-check-tg"></i>
            </div>
            <p class="current-step"><?php echo $this->__($point['label']) ?></p>
        </div>
    <?php endforeach; ?>
    </div>
</div>

<div class="progress-bar-order-mobile mobile-show">
    <div id="progress-bar-mobile" class="progress-bar-mobile step<?php echo $this->getCurrentProgressStep()?>">
        <div class="progress-line">
            <div class="pouring"></div>
        </div>
        <?php $steps = $this->getProgressSteps() ?>
        <div class="progress-dots">
            <?php $i = 0; foreach ($steps as $step): $i++; ?>
                <div class="progress-col-4">
                    <div class="progress-dot progress-dot<?=$i?>"></div>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="progress-steps">
            <?php $i = 0; foreach ($steps as $step): $i++; ?>
                <div class="progress-col-4">
                    <div class="progress-step progress-step<?=$i?>"><p><?php echo $this->__($step['label']) ?></p></div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<a href="<?php echo $this->getUrl('sales/order/tracking', array('order_id' => $this->getOrder()->getId())); ?>" class="more-inf">More information</a>