<?php /* @var Blackbox_Epace_Block_Adminhtml_Epace_View_Statistics_Abstract $this*/ ?>
<div class="col-md-6">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account">Statistic Information</h4>
            <div class="tools"></div>
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                Statistics data is empty.
            </div>
        </div>
    </div>
</div>