<?php
/**
 * @var Blackbox_Notification_Block_Log_View_Form $this
 */
?>
<?php $event = $this->getLog() ?>
<div class="row">
    <div class="col-md-6">
        <!--Event Information-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account">Event Information</h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list">
                    <tbody><tr>
                        <td class="label"><label>Event Date</label></td>
                        <td class="value"><strong><?=$event->getCreatedAt()?></strong></td>
                    </tr>
                    <tr>
                        <td class="label"><label>Event Type</label></td>
                        <td class="value"><strong><?=$this->getType()?></strong></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <!--Event Params Information-->
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-account">Event Params</h4>
                <div class="tools"></div>
            </div>
            <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <?php foreach ($event->getParams() as $label => $value): ?>
                            <tr>
                                <td class="label"><label><?=$label?></label></td>
                                <td class="value"><strong><?=$value?></strong></td>
                            </tr>
                        <?php endforeach ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
