<?php /** @var Blackbox_TenderGreens_Block_Sales_Tracking_Progress $this */ ?>
<div class="progress-bar-order progress-<?php echo $this->getProgressBarStep() ?>-step-track ">

    <div class="points-progress">
        <div class="progress-point ">

            <div class="progress-point-circle-track">
                <i class="fas fa-check-tg"></i>
            </div>
            <div class="buttracktext1">
                <p class="current-step-track">SHIPPING<br> <?php echo $this->getShippingDate() ?></p></div>
        </div>
        <div class="progress-point">

            <div class="progress-point-circle-track">
                <i class="fas fa-check-tg"></i>
            </div>
            <div class="buttracktext2">
                <p>ORDER<br>INFORMATION</p></div>
        </div>
        <div class="progress-point">

            <div class="progress-point-circle-track">
                <i class="fas fa-check-tg"></i>
            </div>
            <div class="buttracktext3">
                <p>ORDER<br>DELIVERY</p></div>
        </div>
        <div class="progress-point">

            <div class="progress-point-circle-track">
                <i class="fas fa-check-tg"></i>
            </div>
            <div class="buttracktext4">
                <p>COURIER<br> DELIVERY </p></div>
        </div>
        <div class="progress-point">

            <div class="progress-point-circle-track">
                <i class="fas fa-check-tg"></i>
            </div>
            <div class="buttracktext5">
                <p>ORDER<br> ISSUED</p></div>
        </div>
    </div>
</div>