<?php /** @var Blackbox_TenderGreens_Block_Sales_Tracking_Progress $this */ ?>
<?php
$currentProgressNumber = $this->getCurrentProgressNumber();
$steps = [
    1 => 'shipping',
    2 => 'order information',
    3 => 'order delivery',
    4 => 'order issued'
];
$i = 0;
?>
<div class="trackprogress_progress">
    <!--class ".active-main" for mobile-->
    <?php foreach ($steps as $step => $label): ?>
        <div class="trackprogress_progress_item<?=$currentProgressNumber >= $step ? ' active' : ''?><?=$currentProgressNumber == $step ? ' active-main' : '' ?>">
            <div class="trackprogress_progress_item_step"><?=++$i?></div>
            <div class="title13"><?=$label?></div>
        </div>
    <?php endforeach; ?>
</div>