<?php /** @var Blackbox_TenderGreens_Block_Sales_Tracking_Progress $this */ ?>
<div class="progress-bar-order progress-<?php echo $this->getProgressBarStep() ?>-step-track">
    <div class="points-progress">
        <div class="progress-point ">
            <div class="progress-point-circle-track">
                <i class="fas fa-check-tg"></i>
            </div>
            <div class="buttracktext1 step1">
                <p class="current-step-track">SHIPPING <?php echo $this->getShippingDate() ?></p>
            </div>
            <div class="buttracktext1 step2">
                <p class="current-step-track">ORDER INFORMATION</p>
            </div>
            <div class="buttracktext1 step3">
                <p class="current-step-track">ORDER DELIVERY</p>
            </div>
            <div class="buttracktext1 step4">
                <p class="current-step-track">COURIER DELIVERY</p>
            </div>
            <div class="buttracktext1 step5">
                <p class="current-step-track">ORDER ISSUED</p>
            </div>
        </div>
    </div>
</div>
