<table bgcolor="#ffffff" width="600" border="0" cellpadding="0" cellspacing="0" style="margin:0;padding:0;">
    <tr>
        <td colspan="4" height="25"></td>
    </tr>
    <?php foreach ($this->getTotals() as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else: ?>
            <tr class="<?php echo $_code ?>">
                <td width="34"></td>
                <td width="285" class="t6" valign="top">
                    <?php if ($_total->getStrong()): ?>
                        <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
                    <?php else: ?>
                        <?php echo $this->escapeHtml($_total->getLabel()); ?>
                    <?php endif ?>
                </td>
                <td width="247" class="t6" valign="top">
                    <?php if ($_total->getStrong()): ?>
                        <strong><?php echo $this->formatValue($_total) ?></strong>
                    <?php else: ?>
                        <?php echo $this->formatValue($_total) ?>
                    <?php endif ?>
                </td>
                <td width="34"></td>
            </tr>
        <?php endif ?>
    <?php endforeach; ?>
    <tr>
        <td colspan="4" height="25"></td>
    </tr>
    <tr>
        <td colspan="4" height="1" bgcolor="#eaeaea"></td>
    </tr>
</table>
